spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_kim?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: movie
    password: movie
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

ticket:
  inventory:
    key-prefix: "ticket"
    issued-token-ttl: 30m
